name: Do release PR or GitHub release
on:
  push:
    branches:
    - 1.1

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: werf/third-party-release-please-action@werf
      with:
        default-branch: 1.1
        release-type: go
        bump-minor-pre-major: true
        bump-patch-for-minor-pre-major: true
#        release-notes-header: ''
#        release-notes-footer: ''
